### ISSUE TITLE
Build fails with unitiliazed constant Gem::SafeYAML error

### ISSUE THREAD

**Issue by zabetak** [vlsi/calcite-test-dataset#26]
After installing vagrant & virtualbox I tried to build the VM using mvn install but it fails at provisioning step with the following error:
...
Installing gem thor-0.20.3
Downloading gem thor-0.20.3.gem
GET https://rubygems.org/gems/thor-0.20.3.gem
Fetching: thor-0.20.3.gem (100%)
200 OK
ERROR:  While executing gem ... (NameError)
    uninitialized constant Gem::SafeYAML

**Setup**
Vagrant 2.2.4
Virtual Box Version 6.0.4 r128413 (Qt5.6.3)
MacOS High Sierra 10.13.6 
Java version: 9.0.1
Apache Maven 3.5.1

**Comment by risdenk** [comment]
@zabetak I'm pretty sure this issue is fixed by PR #25

**Comment by risdenk** [comment]
Merged PR #25 so you shouldn't see this error anymore.

**Comment by zabetak** [comment]
I can confirm it is fixed! Thanks!
