### ISSUE TITLE
Remove Druid middle manager

### ISSUE THREAD

**Issue by julianhyde** [vlsi/calcite-test-dataset#9]
Remove Druid middle manager, to save memory, as it is the same as overlord.

See comment from @b-slim https://github.com/vlsi/calcite-test-dataset/pull/7/files/7f31d4768ccfa2e5e933251c4c809d17f9cf065b#r61689619

> i know this PR is merged, but if you want to save same mem space within the VM, you can avoid having a middle manager. In Druid Middle manager are the same as overlord and they are used for horizontal scalability.

**Comment by julianhyde** [comment]
In run.sh, I tried removing the lines

``` bash
echo Start Druid middle manager node
java `conf middleManager | xargs` \
    -cp conf-quickstart/druid/_common:conf-quickstart/druid/middleManager:lib/* \
    io.druid.cli.Main server middleManager 2>&1 >middleManager.log &
sleep 30
```

and rebuilt the VM, but Calcite's tests started failing. Each query returned no rows, so I presume the load process was broken. Giving up.

**Comment by b-slim** [comment]
@julianhyde what is the error ?

**Comment by julianhyde** [comment]
I didn't see an error. I didn't want to spend ages trawling through logs. I just saw that all queries were returning 0 rows, whereas with middle-manager enabled the queries gave the correct results.

**Comment by b-slim** [comment]
the default config file `conf/druid/overlord/runtime.properties` used to start the overlord has the property `druid.indexer.runner.type=remote` in order to fix it it needs to be `druid.indexer.runner.type=local`.
i am not sure if the memory issue is worth modifying the default file. it is your call.
